// SPDX-License-Identifier: BSD-3-Clause-Attribution
pragma solidity >=0.4.22 <0.9.0;

import "@openzeppelin/contracts/finance/PaymentSplitter.sol";

/// @title SpectrrPaymentSplitter
/// @author Supergrayfly
/// @notice This contract receives and distributes the fees generated by Spectrr Finance to different receivers.
contract SpectrrPaymentSplitter is PaymentSplitter {
    address[] private receivers = [
        0x8E8Ca9077880e206a7D04d2A4fEcF8d188fcD7fA,
        0x590eE5A745bC5b738d553C28f70A72f96F12Fe93,
        0x369b7427715b51af87869289DbE766762164e7D8
    ];
    uint256[] private receiversShares = [40, 30, 30];

    constructor() PaymentSplitter(receivers, receiversShares) {}
}
